# Generated by Django 5.2.5 on 2025-08-22 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='runtime',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
